language: scala
scala:
- 2.11.4
jdk:
- oraclejdk7
sudo: false
branches:
  only:
  - master
  - /^[0-9].[0-9].[0-9]$/
cache:
  directories:
  - $HOME/.m2
before_install:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && echo "Not a PR Build" && [ "IS_${TRAVIS_TAG}"
  != "IS_" ] && echo "Is tag build $TRAVIS_TAG" || echo "."'
- '[ "IS_${TRAVIS_TAG}" != "IS_" ] && mvn versions:set -DnewVersion=$TRAVIS_TAG ||
  true'
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
before_script:
- test "$TRAVIS_PULL_REQUEST" == "false" && git clone -b travis `git config --get
  remote.origin.url` target/travis || true
script:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && echo "Deploying..." && mvn deploy --settings
  target/travis/settings.xml || echo "Testing..." && mvn test -B'
after_success:
- '[ "$TRAVIS_TAG" != "" ] && mvn site-deploy -P github-site -Dgithub.global.oauth2Token=$GITHUB_TOKEN
  || true'
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "$TRAVIS_TAG" = "" ] && mvn scoverage:report
  coveralls:report || true'
env:
  global:
  - MAVEN_OPTS="-Xmx1024m -XX:MaxPermSize=256m"
  - secure: UJ5eT0vAspV/RsDjnT2q99NRQn/jIHPFy/QKBHAAvAXmFLXz38WUaR9I5tunxdu/6oe16p69MUCsalqdhObT6BTyCOugLTSHSypbW0RS5DnlDCcXuIpRc5RD+sMm+aLzBfT/0YCPJH3e8htpN6Ni1IXSaJDxq6Q9HWWLUbeJL5+mW83llPMoy4mXEdMexbAui6EUT89UZjre/sLqOHdJchobPQ+nXS5RZN/TYeoAqcmDom0b0f6iSkzTAZqVcqRLJL5SJq0yEXY/lpfDlpwg6aoANGcw0VyB9T86mLLf8KzAQgXxdNkzKMcEwcOKnmicm6sLNIsYLHhJqBZr93r2YOuaplo0TEU4mCCkhdLUrk+w+EjqGBoFP71RsXihd1kY1nj1A8ML03Cqo9bpgT2pEKLwwu66ZS/scPURfMZzYwxHYHRTeo7oZirV6CY1EJUd2nnK+wZOekylXYw3W1OwMC03Z4dH7x68Bois50nA19zWZvGmVbcdsLPOiVPGGy4icG3fO7oA30kWdMb/3CGNiQ85IjRwC+TZX3u/+ezEwDnpU2e7ELnBJIgDS4gBSXiKy8tVJ4Hr/fxrnzy1wMJzfMNTxxIvT97EjoIB8+OUrPCZR9JuZ0qtdWmUGmg+d1Fik4Y5gFkcEJVXaQSqYQBDh4BGgnnc1dhALkW78tOc988=
  - secure: ePrgbDzUP+ni6IUSD2IgwmeL488KTvxP/l4VwTnil68g1OPGpVM7q8wx76tiq7mIqKeuC7JaX/Ke5iOKHXK5xHSAFxaBVNkeAG1sxmdPdo2UbfSf+j9EqOV14ySpk+7mLeSiWfF7HdtXKb9TMdJWYnSW/hDnZPxptyZvJGyk72rpWIaPPZpfWMgt4I6vFc5FqbbR6IP/auBDJyD0lNjd+iR+VGtHLw1EyEXJCloFysk9DW3cnwd2q2rEUTURXH5DMuS0tN5e21FHLTZoB9Hn8WoQElmBYIqs8aPBO16lewrQsfCjKsfHrQBSRmgKxCIoLdufpOeY0yTtM6oM4sq0VNwhBbBcZIEJWnhDcv75F5me6trN/cpQ6Nav6UMX8jPrek4mvcPLnQ0an8wn/YQsyKqRCxKgYyBgJtqgBIbCjtYwKuJo36GuOJF+nrPYO3cNwkFsdehKYhsyoyhtlBSs3cJmOulIBLOh5365UAyJVCCKcZUnWQubpTXBL83OTp2BeUQ8oUMPpVgerIA/3TgQ1zHEV/33Hr1e3dF9iuGMpe5ReLyzGLWCasqqPvasmbHaC8HZp8eZmAJoxWQGq6Ixci4MkILgHbLCJfO8h9AvkZFLxbcbseVJFm5VXYoT4d4Ub4dsBxMtE86GJXsDA9uWWTO2Aq9Ll8YfUfO4d6SblLo=
  - secure: nf1cJWYOlLPSya3INlrQL1EA03T+nUgLzeRoQ0jKxIvu6nWQcMCxv8xyzeAdP+6y4x77ZhQkWIZBqoQYXuW+8rwJUogPB/AhRyZjCtUrzfDRrkeFQlFZlYly49lYxOpLmEfsY6/E+NnMDEnudkgKuxr2P7+d7L5FIevooeWBWoneTCB8k0ioNYVzasdWFs/R1qIvDaXmslWcLVviFkpI97MyH5FSGbT5fYKu7W3hUr1v6uHe2i9CPc45aQED7YijTkP0iDcKsDiamKAPJmhqTzJBcH+P1cJyrKB4VbMsNwCRyDtGBVLNwfUZ51lcDeC+XFJ4WU7OKQCkueUNmcLo/tm6iAmRbzrc7wXpDYDgDUxJzKhwxkqSMOwTruuho3eKyvIJ6rG2lNAxomXnF2riRcP3vUz1q8iurCLX58vcMvauUaMbF4h+C9NkhOf4KyoKNtMyJTd6WIeBPNCYkMinazl6YYjUWo6wY/u/JMzMEL/bQ8S/7pLttp0clyQ7gLMV8r/C4STfPvEAXijUjPd/h9Q+mO00DAqUk/bA6EUM1EBjxMANyTf3LLH+4h4T8quLynqvtktjnefkoWmEnHrv/2rrqv45O3MeSg4aInkOAJ/qvjAl9IcaomctBRayA/BU44OBbZg5PzN0rFwZTsphT1YWciTwSV4v6j+dxiRFz8w=
